### ISSUE TITLE
allowParams should be a table and not an array.

### ISSUE THREAD

**Issue by pmusa** [DhavalKapil/elasticsearch-lua#14]
Instead of having the following which forces a loop to verify

```
Scroll.allowedParams = {
  "scroll",
  "scroll_id"
}
```

we should have the following in which the lookup is direct.

```
Scroll.allowedParams = {
  "scroll" = true,
  "scroll_id" = true
}
```

**Comment by DhavalKapil** [comment]
What is the reason for this?

**Comment by pmusa** [comment]
The reason is that right now (with an array) you need to build a double loop to verify parameters:

```
for k,_ in pairs(params) do for _,v in pairs(allowParams) do if k == v then ...  end end end
```

while with a table you only need one loop.

```
for k,_ in pairs(params) do if allowParams[k] then ... end end
```

**Comment by DhavalKapil** [comment]
Yeah that's right :+1:
