### ISSUE TITLE
what happened? Msearch.lua

### ISSUE THREAD

**Issue by SeeWei1985** [DhavalKapil/elasticsearch-lua#24]
luarocks install --server=http://luarocks.org/manifests/dhavalkapil elasticsearch
Warning: falling back to curl - install luasec to get native HTTPS support
Installing http://luarocks.org/manifests/dhavalkapil/elasticsearch-scm-0.rockspec...
Using http://luarocks.org/manifests/dhavalkapil/elasticsearch-scm-0.rockspec... switching to 'build' mode
Cloning into 'elasticsearch-lua'...
remote: Counting objects: 348, done.
remote: Compressing objects: 100% (190/190), done.
remote: Total 348 (delta 245), reused 215 (delta 154), pack-reused 0
Receiving objects: 100% (348/348), 115.52 KiB | 142.00 KiB/s, done.
Resolving deltas: 100% (245/245), done.
Checking connectivity... done.
stat: cannot stat ‘src/elasticsearch/endpoints/Msearch.lua’: No such file or directory

Error: Build error: Failed installing src/elasticsearch/endpoints/Msearch.lua in /usr/local/openresty/luajit/lib/luarocks/rocks/elasticsearch/scm-0/lua/elasticsearch/endpoints/Msearch.lua

**Comment by DhavalKapil** [comment]
Hi, I've updated the rockspec with some of the changes. It should be fixed now. Thanks for pointing out.

**Comment by SeeWei1985** [comment]
Thank you
