### ISSUE TITLE
bulk operations abort for large sizes

### ISSUE THREAD

**Issue by jvburnes** [DhavalKapil/elasticsearch-lua#25]
Even though you can construct large bulk bodies, the :bulk API method runs out of memory for large sizes that are well within a bulk operation size.  I have records that are approximately 300 bytes each and bulk inserts work okay for 512 insert bodies, but start slowing down drastically at 2048 and somewhere around 4096 start raising "luajit: not enough memory" exceptions.

I'm not sure why this happens, although I assume it's because you're trying to serialize the entire bulk table into the outgoing client JSON TCP stream at the same time rather than generating smaller buffers.

**Comment by DhavalKapil** [comment]
I think you are right about the error. I will surely check it. The `Bulk` API method that is provided in this client is a direct wrapper over the low level 'Bulk' API provided by Elasticsearch. I purposely didn't provide any custom computation over it to enable other developers to customize it as per their use cases.
However, what you say is a pretty common use case and I am planning to provide a separate function for processing large buffers in `helpers.lua`.
Thanks!

**Comment by jvburnes** [comment]
Another nice to have would be something that takes advantage of the
proposed short reply for bulk requests.  It's insane that a bulk request
with 10k inserts has a reply with 10k responses even if 9999 of them
executed properly.   They should just use the short-reply suggestion and
include a list of the actions that failed.

It's amazing how much CPU and memory is wasted these days. :)

Jim Burnes

**Comment by jvburnes** [comment]
I was just reading the Endpoint.lua code and the problem is that you should
be doing a table.concat rather than the loop which json encodes the
argument and concatenates it.  That will definitely generate a garbage
collection nightmare and runaway memory management issues.

**Comment by DhavalKapil** [comment]
As far as I know, short replies for bulk requests in Elasticsearch is still not implemented - https://github.com/elastic/elasticsearch/issues/2661. Anyways it is a feature of Elasticsearch. Point me if I'm wrong.

> It's amazing how much CPU and memory is wasted these days. :)

It's sad that the worth of something decreases when its availability increases :)

> the problem is that you should be doing a table.concat rather than the loop

Sure, I'll look into it.

**Comment by jvburnes** [comment]
I believe the fix is something like this in Endpoint:setBody

.
.
.
-- Bulk body is present
local jFrags = {}
for id, item in pairs(body) do
  jFrags[#jFrags+1] = parser.jsonEncode(item)
end
self.body = table.concat(jFrags,"\n")
.
.
.

There might be similar code for the decode side also, but I didn't check.

Let me know.

**Comment by pmusa** [comment]
The concat change helps a lot. I did a simple test here and the difference is huge.
In regards to the response, this is an Elasticsearch decision and we make it as transparent as possible. So, as far as they do not implement this option there is no point in doing it on the client side. Thank you very much for the suggestion. I would like to encourage you to create a PR @jvburnes

**Comment by jvburnes** [comment]
Did you want me to create a PR for this patch?  Did you already modify the
code / submit a patch?

Thx

JB

**Comment by jvburnes** [comment]
I think you broke your rocks installer.  The "Cat.lua" file isn't being
installed and that at least breaks the require.

JB

**Comment by jvburnes** [comment]
also Snapshot and Tasks

**Comment by DhavalKapil** [comment]
Fixed in https://github.com/DhavalKapil/elasticsearch-lua/commit/9f037ae9337fe5bd8fdb959bdfbd590bcc66d659
Thanks!

**Comment by jvburnes** [comment]
No problem.  I'm now getting about 6000 indexes a second for records of
about 300 bytes of which three of the fields are being indexed (of about
12).  This is on a virtual machine with 2 vcpus on ElasticSearch 5.  That's
about 3x the fastest I got before and it's not crashing on bulk index
operations of size 32768.

**Comment by pmusa** [comment]
I did not change any code yet. Just did a small Lua test comparing .. to table.concat. If you have the change in your code base, please open a PR.

**Comment by jvburnes** [comment]
Okay.  If I have some time today I'll submit.
