### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by stml2013** [DhavalKapil/elasticsearch-lua#27]
luarocks install --server=http://luarocks.org/dev elasticsearch

**cp: cannot stat `src/elasticsearch/Cat.lua': No such file or directory**
Error: Build error: Failed installing src/elasticsearch/Cat.lua in /usr/lib/luarocks/rocks/elasticsearch/scm-0/lua/elasticsearch/Cat.lua

**Comment by DhavalKapil** [comment]
Hi, you're trying to install a previous version. Try this instead:

```sh
luarocks install elasticsearch
```

**Comment by DhavalKapil** [comment]
@stml2013 are you able to install elasticsearch now?
