### ISSUE TITLE
Endpoint "ping" not working

### ISSUE THREAD

**Issue by pmusa** [DhavalKapil/elasticsearch-lua#9]
Call to ping return error as it tries to parse body response from HEAD request. Maybe we should verify the "self:getMethod" before decoding the body.

Code to reproduce error:
local es = require"elasticsearch"
local c = es:client()
c:ping()

lua: /usr/local/share/lua/5.3/endpoints/Endpoint.lua:99: Expected value but found T_END at character 1
stack traceback:
    [C]: in function 'cjson.decode'
    /usr/local/share/lua/5.3/endpoints/Endpoint.lua:99: in function 'endpoints.Endpoint.request'
    /usr/local/share/lua/5.3/Client.lua:52: in function 'Client.requestEndpoint'
    /usr/local/share/lua/5.3/Client.lua:77: in function 'Client.ping'
    es.lua:7: in main chunk
    [C]: in ?

**Comment by DhavalKapil** [comment]
This bug occurs because the reponse body returned is `""`. i.e. an empty string. This is passed to the cjson library which is unable to parse it.
